package com.example.toshiba.rickandmorty.Database;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHARACTER".
*/
public class CharacterDao extends AbstractDao<Character, Long> {

    public static final String TABLENAME = "CHARACTER";

    /**
     * Properties of entity Character.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Status = new Property(2, String.class, "status", false, "STATUS");
        public final static Property Species = new Property(3, String.class, "species", false, "SPECIES");
        public final static Property Type = new Property(4, String.class, "type", false, "TYPE");
        public final static Property Gender = new Property(5, String.class, "gender", false, "GENDER");
        public final static Property OriginId = new Property(6, Long.class, "originId", false, "ORIGIN_ID");
        public final static Property LocationId = new Property(7, Long.class, "locationId", false, "LOCATION_ID");
        public final static Property Image = new Property(8, String.class, "image", false, "IMAGE");
        public final static Property Url = new Property(9, String.class, "url", false, "URL");
        public final static Property Created = new Property(10, String.class, "created", false, "CREATED");
    }

    private DaoSession daoSession;

    private Query<Character> location_CharacterOriginListQuery;
    private Query<Character> location_CharacterLocationListQuery;

    public CharacterDao(DaoConfig config) {
        super(config);
    }
    
    public CharacterDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHARACTER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"STATUS\" TEXT," + // 2: status
                "\"SPECIES\" TEXT," + // 3: species
                "\"TYPE\" TEXT," + // 4: type
                "\"GENDER\" TEXT," + // 5: gender
                "\"ORIGIN_ID\" INTEGER," + // 6: originId
                "\"LOCATION_ID\" INTEGER," + // 7: locationId
                "\"IMAGE\" TEXT," + // 8: image
                "\"URL\" TEXT UNIQUE ," + // 9: url
                "\"CREATED\" TEXT);"); // 10: created
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHARACTER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Character entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(3, status);
        }
 
        String species = entity.getSpecies();
        if (species != null) {
            stmt.bindString(4, species);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(5, type);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(6, gender);
        }
 
        Long originId = entity.getOriginId();
        if (originId != null) {
            stmt.bindLong(7, originId);
        }
 
        Long locationId = entity.getLocationId();
        if (locationId != null) {
            stmt.bindLong(8, locationId);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(9, image);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(10, url);
        }
 
        String created = entity.getCreated();
        if (created != null) {
            stmt.bindString(11, created);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Character entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(3, status);
        }
 
        String species = entity.getSpecies();
        if (species != null) {
            stmt.bindString(4, species);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(5, type);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(6, gender);
        }
 
        Long originId = entity.getOriginId();
        if (originId != null) {
            stmt.bindLong(7, originId);
        }
 
        Long locationId = entity.getLocationId();
        if (locationId != null) {
            stmt.bindLong(8, locationId);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(9, image);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(10, url);
        }
 
        String created = entity.getCreated();
        if (created != null) {
            stmt.bindString(11, created);
        }
    }

    @Override
    protected final void attachEntity(Character entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Character readEntity(Cursor cursor, int offset) {
        Character entity = new Character( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // status
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // species
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // type
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // gender
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // originId
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // locationId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // image
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // url
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // created
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Character entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStatus(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSpecies(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setType(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGender(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOriginId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setLocationId(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setImage(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setUrl(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCreated(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Character entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Character entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Character entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "characterOriginList" to-many relationship of Location. */
    public List<Character> _queryLocation_CharacterOriginList(Long originId) {
        synchronized (this) {
            if (location_CharacterOriginListQuery == null) {
                QueryBuilder<Character> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.OriginId.eq(null));
                location_CharacterOriginListQuery = queryBuilder.build();
            }
        }
        Query<Character> query = location_CharacterOriginListQuery.forCurrentThread();
        query.setParameter(0, originId);
        return query.list();
    }

    /** Internal query to resolve the "characterLocationList" to-many relationship of Location. */
    public List<Character> _queryLocation_CharacterLocationList(Long locationId) {
        synchronized (this) {
            if (location_CharacterLocationListQuery == null) {
                QueryBuilder<Character> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.LocationId.eq(null));
                location_CharacterLocationListQuery = queryBuilder.build();
            }
        }
        Query<Character> query = location_CharacterLocationListQuery.forCurrentThread();
        query.setParameter(0, locationId);
        return query.list();
    }

}
