package com.example.toshiba.rickandmorty.Database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JOIN_CHARACTER_WITH_EPISODES".
*/
public class JoinCharacterWithEpisodesDao extends AbstractDao<JoinCharacterWithEpisodes, Long> {

    public static final String TABLENAME = "JOIN_CHARACTER_WITH_EPISODES";

    /**
     * Properties of entity JoinCharacterWithEpisodes.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CharacterId = new Property(1, Long.class, "characterId", false, "CHARACTER_ID");
        public final static Property EpisodeId = new Property(2, Long.class, "episodeId", false, "EPISODE_ID");
    }


    public JoinCharacterWithEpisodesDao(DaoConfig config) {
        super(config);
    }
    
    public JoinCharacterWithEpisodesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JOIN_CHARACTER_WITH_EPISODES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CHARACTER_ID\" INTEGER," + // 1: characterId
                "\"EPISODE_ID\" INTEGER);"); // 2: episodeId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JOIN_CHARACTER_WITH_EPISODES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JoinCharacterWithEpisodes entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long characterId = entity.getCharacterId();
        if (characterId != null) {
            stmt.bindLong(2, characterId);
        }
 
        Long episodeId = entity.getEpisodeId();
        if (episodeId != null) {
            stmt.bindLong(3, episodeId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JoinCharacterWithEpisodes entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long characterId = entity.getCharacterId();
        if (characterId != null) {
            stmt.bindLong(2, characterId);
        }
 
        Long episodeId = entity.getEpisodeId();
        if (episodeId != null) {
            stmt.bindLong(3, episodeId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JoinCharacterWithEpisodes readEntity(Cursor cursor, int offset) {
        JoinCharacterWithEpisodes entity = new JoinCharacterWithEpisodes( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // characterId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // episodeId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JoinCharacterWithEpisodes entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCharacterId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setEpisodeId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JoinCharacterWithEpisodes entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JoinCharacterWithEpisodes entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JoinCharacterWithEpisodes entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
